# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        elixir: ["1.18.2"]
        otp: ["27.0"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }} # [Required] Define the Elixir version
          otp-version: ${{ matrix.otp }} # [Required] Define the Erlang/OTP version
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Restore PLT cache
        uses: actions/cache@v3
        with:
          path: _build/dev/*.plt
          key: ${{ runner.os }}-plt-${{ hashFiles('**/mix.lock') }}-${{ matrix.elixir }}-${{ matrix.otp }}
          restore-keys: |
            ${{ runner.os }}-plt-${{ hashFiles('**/mix.lock') }}-${{ matrix.elixir }}-${{ matrix.otp }}
      - name: Install difftastic
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -L https://github.com/Wilfred/difftastic/releases/latest/download/difft-x86_64-unknown-linux-gnu.tar.gz | tar xz
          sudo mv difft /usr/local/bin/
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
      - name: Run dialyzer
        run: mix dialyzer
